#!/bin/bash

if [[ $# > 0 ]]; then
    for opt in $@; do
      case ${opt,,} in
        "black") tput setaf 0;;
        "red") tput setaf 1;;
        "green") tput setaf 2;;
        "yellow") tput setaf 3;;
        "blue") tput setaf 4;;
        "magenta") tput setaf 5;;
        "cyan") tput setaf 6;;
        "white") tput setaf 7;;
        "powder_blue") tput setaf 153;;
        "lime_yellow") tput setaf 190;;
        "bold") tput bold;;
        "blink") tput blink;;
        "reverse") tput smso;;
        "underline") tput smul;;
        "reset") tput sgr0;;
      esac
    done
else
    tput sgr0
fi
